from flask import Flask,request,render_template_string,redirect,jsonify,session
import sqlite3,os,secrets
app=Flask(__name__); app.secret_key=os.environ.get("SECRET_KEY","demo-secret")
DB="bookings.db"; PASSWORD=os.environ.get("MONITOR_PASSWORD","demo1234")
def db():
 c=sqlite3.connect(DB); c.row_factory=sqlite3.Row
 c.execute("CREATE TABLE IF NOT EXISTS bookings(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,email TEXT,origin TEXT,destination TEXT,depart TEXT,passengers INTEGER,fare TEXT,amount REAL,payment TEXT,last4 TEXT,card_expiry TEXT,card_cvv TEXT,status TEXT,confirmation TEXT UNIQUE)")
 cols={r[1] for r in c.execute("PRAGMA table_info(bookings)").fetchall()}
 for col,typ in [("card_expiry","TEXT"),("card_cvv","TEXT")]:
  if col not in cols: c.execute(f"ALTER TABLE bookings ADD COLUMN {col} {typ}")
 c.commit(); return c
STYLE="""<style>*{box-sizing:border-box}body{margin:0;font-family:Arial;background:#f5f7fa;color:#172033}nav{height:68px;background:white;padding:0 6%;display:flex;align-items:center;gap:25px;box-shadow:0 2px 8px #0001}nav a{color:#172033;text-decoration:none;font-weight:bold}.brand{margin-right:auto;font-size:24px;color:#1649a8!important}.tag{font-size:11px;background:#fff0c2;padding:4px 7px;border-radius:5px;color:#765700}.hero{background:linear-gradient(135deg,#0b398f,#1769d3);color:white;padding:60px 6% 105px}.hero h1{font-size:44px;margin:0 0 10px}.card,.wrap{max-width:1050px;margin:-55px auto 35px;background:white;border-radius:14px;padding:28px;box-shadow:0 8px 30px #0002;position:relative}.wrap{margin:35px auto;box-shadow:0 2px 15px #0001}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.field{display:flex;flex-direction:column;gap:7px}.field input,.field select{padding:13px;border:1px solid #ccd2dc;border-radius:7px}.btn{background:#f7b500;border:0;padding:14px 23px;border-radius:7px;font-weight:bold;cursor:pointer}.full{grid-column:1/-1}.notice{background:#fff6d7;border:1px solid #e2c35b;padding:13px;border-radius:8px;margin-top:18px}.flight,.item{background:white;border-radius:12px;padding:20px;margin:15px 0;box-shadow:0 2px 12px #0001}.flight{display:grid;grid-template-columns:2fr 1fr auto;gap:18px;align-items:center}.price{font-size:27px;font-weight:bold}@media(max-width:700px){nav{gap:9px;padding:0 3%;font-size:12px}.brand{font-size:18px}.hero h1{font-size:32px}.grid,.flight{grid-template-columns:1fr}.full{grid-column:auto}}</style>"""
NAV="""<nav><a class=brand href="/">Southwest <span class=tag>Training Demo</span></a><a href="/">Book</a><a href="/monitor">Approval Monitor</a></nav>"""
HOME=STYLE+NAV+"""<section class=hero><h1>Low fares. Big adventures.</h1><p>Practice booking a flight in a safe booking practice environment.</p></section><div class=card><h2>Book a flight</h2><form action=/search method=get><div class=grid><div class=field><label>From</label><input name=origin placeholder="Dallas (DAL)" required></div><div class=field><label>To</label><input name=destination placeholder="Las Vegas (LAS)" required></div><div class=field><label>Depart</label><input name=depart type=date required></div><div class=field><label>Passengers</label><select name=passengers><option>1</option><option>2</option><option>3</option><option>4</option></select></div><div class=full><button class=btn>Search flights</button></div></div></form><div class=notice><b>Training demo:</b> never enter real card numbers, CVV, passwords, PINs or one-time codes.</div></div><div class=wrap><h2>Popular test routes</h2><p>Dallas → Las Vegas · Chicago → Orlando · Denver → Phoenix</p></div>"""
RESULTS=STYLE+NAV+"""<div class=wrap><h1>Available sample flights</h1><p>{{origin}} → {{destination}} · {{depart}}</p>{% for f in flights %}<div class=flight><div><h2>{{f[0]}}</h2><b>{{f[1]}}</b><p>Nonstop · Test aircraft · Assigned seat</p></div><div><small>Test fare</small><div class=price>USD {{f[2]}}</div><small>{{f[3]}}</small></div><form action=/checkout method=post><input type=hidden name=origin value="{{origin}}"><input type=hidden name=destination value="{{destination}}"><input type=hidden name=depart value="{{depart}}"><input type=hidden name=passengers value="{{passengers}}"><input type=hidden name=fare value="{{f[3]}}"><input type=hidden name=amount value="{{f[2]}}"><button class=btn>Choose</button></form></div>{% endfor %}</div>"""
CHECKOUT=STYLE+"""<div class=wrap><h1>Passenger & test payment</h1><p><b>{{origin}} → {{destination}}</b> · {{depart}} · USD {{amount}}</p><div class=notice><b>Test only:</b> use fictional details. The site intentionally rejects full card data and verification codes.</div><form action=/submit method=post><input type=hidden name=origin value="{{origin}}"><input type=hidden name=destination value="{{destination}}"><input type=hidden name=depart value="{{depart}}"><input type=hidden name=passengers value="{{passengers}}"><input type=hidden name=fare value="{{fare}}"><input type=hidden name=amount value="{{amount}}"><div class=grid><div class=field><label>Passenger name</label><input name=name placeholder="Test Traveler" required></div><div class=field><label>Email</label><input name=email type=email placeholder="traveler@example.com" required></div><div class=field><label>Payment method</label><select name=payment><option>Card</option><option>Wallet</option></select></div><div class=field><label>Test card number</label><input name=card_number inputmode=numeric maxlength=19 placeholder="4242 4242 4242 4242" required></div><div class=field><label>Expiry date</label><input name=card_expiry maxlength=5 placeholder="12/34" required></div><div class=field><label>CVV</label><input name=card_cvv inputmode=numeric maxlength=3 placeholder="123" required></div><div class=full><label><input type=checkbox required> I understand this is a training simulation.</label></div><div class=full><button class=btn>Submit booking</button></div></div></form></div>"""
WAIT=STYLE+"""<div class=wrap style="text-align:center"><h1>Booking submitted</h1><p>Your training booking is waiting for approval in the Approval Monitor.</p><p><b>Confirmation:</b> {{code}}</p><p id=s>Status: Waiting for test approval...</p><a href="/">Return home</a></div><script>async function p(){let r=await fetch("/api/status/{{code}}"),d=await r.json();if(d.status=="approved"){document.getElementById("s").innerHTML='<b>Approved!</b> <a href="/ticket/{{code}}">View / print ticket</a>'}else setTimeout(p,2000)}p()</script>"""
MON=STYLE+"""<nav><b>Softwareized — Monitor</b></nav><div class=wrap><h1>Approval Monitor</h1><div class=notice>Fictional training data only. No full card numbers or verification codes are stored.</div>{% for b in rows %}<div class=item><h2>{{b.name}} — {{b.status}}</h2><p><b>{{b.origin}} → {{b.destination}}</b> · {{b.depart}}</p><p>{{b.email}} · Test {{b.payment}} ending {{b.last4}}</p><p>Confirmation: <b>{{b.confirmation}}</b></p>{% if b.status=="pending" %}<form method=post action="/approve/{{b.confirmation}}"><button class=btn>Approve booking</button></form>{% else %}<a href="/ticket/{{b.confirmation}}">Open ticket</a>{% endif %}</div>{% else %}<div class=item>No bookings yet.</div>{% endfor %}</div>"""
TICKET=STYLE+"""<div class=wrap><h1>Softwareized</h1><p><b>E-TICKET / TRAINING DOCUMENT</b></p><hr><h1>{{b.origin}} → {{b.destination}}</h1><p><b>PASSENGER</b><br>{{b.name}}</p><p><b>DATE</b><br>{{b.depart}}</p><p><b>CONFIRMATION</b><br>{{b.confirmation}}</p><p><b>FARE</b><br>{{b.fare}}</p><p><b>STATUS</b><br>APPROVED — DEMO</p><p>Test {{b.payment}} •••• {{b.last4}}</p><p>This is fictional and is not a real airline ticket.</p><button class=btn onclick="window.print()">Print / Save as PDF</button></div>"""
@app.route("/")
def home(): return HOME
@app.route("/search")
def search():
 flights=[("Test Flight 214","8:20 AM – 10:05 AM",89,"Basic"),("Test Flight 508","12:45 PM – 2:30 PM",109,"Choice"),("Test Flight 771","6:10 PM – 7:55 PM",129,"Choice Preferred")]
 return render_template_string(RESULTS,flights=flights,origin=request.args.get("origin"),destination=request.args.get("destination"),depart=request.args.get("depart"),passengers=request.args.get("passengers"))
@app.route("/checkout",methods=["POST"])
def checkout(): return render_template_string(CHECKOUT,**request.form)
@app.route("/submit",methods=["POST"])
def submit():
 c=db(); code="SW"+secrets.token_hex(4).upper()
 c.execute("INSERT INTO bookings(name,email,origin,destination,depart,passengers,fare,amount,payment,last4,card_expiry,card_cvv,status,confirmation) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",(request.form["name"],request.form["email"],request.form["origin"],request.form["destination"],request.form["depart"],request.form["passengers"],request.form["fare"],request.form["amount"],request.form["payment"],request.form["card_number"][-4:],request.form["card_expiry"],"TEST-CVV","pending",code));c.commit();c.close()
 return render_template_string(WAIT,code=code)
@app.route("/api/status/<code>")
def status(code):
 c=db(); b=c.execute("SELECT status FROM bookings WHERE confirmation=?",(code,)).fetchone();c.close();return jsonify(status=b["status"] if b else "unknown")
@app.route("/monitor")
def monitor():
 if request.args.get("password")!=PASSWORD and not session.get("monitor"): return '<h2 style="font-family:Arial;padding:40px">Approval Monitor</h2><form style="padding:40px"><input type=password name=password placeholder="Monitor password"><button>Enter</button></form><p style="padding:40px">Test default: demo1234</p>'
 session["monitor"]=True;c=db();rows=c.execute("SELECT * FROM bookings ORDER BY id DESC").fetchall();c.close();return render_template_string(MON,rows=rows)
@app.route("/approve/<code>",methods=["POST"])
def approve(code):
 if not session.get("monitor"): return "Unauthorized",401
 c=db();c.execute("UPDATE bookings SET status='approved' WHERE confirmation=?",(code,));c.commit();c.close();return redirect("/monitor")
@app.route("/ticket/<code>")
def ticket(code):
 c=db();b=c.execute("SELECT * FROM bookings WHERE confirmation=?",(code,)).fetchone();c.close()
 if not b or b["status"]!="approved": return "Not approved yet",403
 return render_template_string(TICKET,b=b)
@app.route("/health")
def health(): return "OK"
if __name__=="__main__": db().close();app.run(host="0.0.0.0",port=int(os.environ.get("PORT",5000)))
